kind: Deployment
apiVersion: apps/v1
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
        - name: spark-master
          image: anmolrecker/spark-hadoop:3.1
          imagePullPolicy: Always
          command: ["/spark-master"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          volumeMounts:
            - name: azurefileshare
              mountPath: /spark
      volumes:
      - name: azurefileshare
        azureFile:
          secretName: storage-secret
          shareName: spark
          readOnly: false
